name = "stretchworks"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
ANTHROPIC_API_KEY = "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"
